import streamlit as st
import pandas as pd
from fpdf import FPDF
import os
from dotenv import load_dotenv
from google import genai as new_genai   # ✅ NEW SDK

# ✅ LOAD ENV VARIABLES
load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# ✅ INIT CLIENT (SAFE)
client = None
if GEMINI_API_KEY:
    try:
        client = new_genai.Client(api_key=GEMINI_API_KEY)
    except Exception as e:
        st.error(f"Failed to initialize Gemini: {e}")
else:
    st.warning("⚠️ Gemini API key not found. Using fallback AI logic.")


def generate_ai_report(audit_results, is_mitigated=False):
    """
    Member 3: The AI Auditor.
    """
    st.markdown("### 🤖 Member 3: AI Ethical Auditor")

    # 1. Prepare data
    attr = ", ".join(audit_results.get('protected_cols', []))
    gap = audit_results.get('gap', 0)
    is_class = audit_results.get('is_classification', True)
    metric_type = "Fairness Gap (%)" if is_class else "Disparity Ratio (x)"
    status = "Post-Mitigation" if is_mitigated else "Initial Audit"

    # 2. Prompt
    prompt = f"""
You are an expert AI Ethics Consultant.

Status: {status}
Attribute: {attr}
Metric: {metric_type}
Value: {gap}

Write a professional report:
1. Summarize ethical risk
2. Explain impact
3. Give one expert recommendation

Keep it concise and clear.
"""

    # 3. Gemini Call (FIXED)
    try:
        if client:
            response = client.models.generate_content(
                model="gemini-2.0-flash",
                contents=prompt
            )
            report_text = response.text
            source_label = "Generated by Gemini 2.0 Flash"
        else:
            raise Exception("No API Key")

    except Exception as e:
        source_label = "Fallback AI Logic"
        if not is_mitigated:
            report_text = f"""
## Executive Summary
The system was evaluated for fairness across the attribute(s): {attr}. 
A bias score of {gap:.2f} indicates potential disparity in model outcomes.

## Risk Assessment
The current system is categorized as {audit_results.get('risk', 'Unknown')}, suggesting that certain groups may experience unequal treatment.

## Key Insight
The disparity likely arises from imbalanced data representation or indirect proxy variables influencing predictions.

## Recommendation
Apply fairness-aware techniques such as reweighing or bias mitigation preprocessing. Continuous monitoring is recommended to ensure long-term fairness.
"""
        else:
            report_text = f"""
Bias reduced for {attr}.
Model is now more fair.
Recommendation: Monitor continuously.
"""

    # 4. UI + PDF (FIXED DUPLICATE)
    with st.container(border=True):
        # st.write(report_text)
        st.caption(source_label)

        if "pdf_data" not in st.session_state:
            st.session_state.pdf_data = create_pdf(audit_results, report_text)

        # st.download_button(
        #     label="📥 Download PDF Report",
        #     data=st.session_state.pdf_data,
        #     file_name="AI_Ethics_Report.pdf",
        #     mime="application/pdf"
        # )

    return {
        "risk": audit_results.get('risk', 'Unknown'),
        "finding": report_text
    }


def show_proxy_warning(df, protected_col):
    numeric_df = df.select_dtypes(include=['number'])

    if protected_col in df.columns and not numeric_df.empty:
        temp_df = df.copy()
        temp_df[protected_col] = temp_df[protected_col].astype('category').cat.codes

        corr = temp_df.corr(numeric_only=True)[protected_col].abs().sort_values(ascending=False)
        proxies = corr[1:3]

        if not proxies.empty and proxies.iloc[0] > 0.5:
            st.warning(
                f"Proxy Detected: **{proxies.index[0]}** is highly correlated ({proxies.iloc[0]:.2f}) with **{protected_col}**."
            )


def sanitize_text(text):
    if not isinstance(text, str):
        text = str(text)

    replacements = {
    '🔴': '',
    '🟡': '',
    '🟢': ''
}
    text = " ".join(text.split())

    for k, v in replacements.items():
        text = text.replace(k, v)

    return text.encode('latin-1', 'ignore').decode('latin-1')


def create_pdf(audit_results, report_text):
    pdf = FPDF()
    pdf.add_page()

    protected = sanitize_text(", ".join(audit_results.get('protected_cols', [])))
    gap = sanitize_text(str(audit_results.get('gap',0)))
    risk = sanitize_text(audit_results.get('risk','Unknown'))
    report_text = sanitize_text(report_text)

    pdf.set_font("Arial", 'B', 18)
    pdf.cell(0, 12, "FairFrame AI Audit Report", ln=True, align='C')

    pdf.ln(10)

    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 8, f"Protected Attribute: {protected}", ln=True)
    pdf.cell(0, 8, f"Bias Score: {gap}", ln=True)
    pdf.cell(0, 8, f"Risk: {risk}", ln=True)

    pdf.ln(10)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "AI Ethical Report", ln=True)

    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 8, report_text)

    return pdf.output(dest='S').encode('latin-1', errors='replace')

def generate_micro_insight(context_type, df=None, target=None, protected_cols=None, stats=None):
    """
    Generates short real-time insights for each step.
    """

    try:
        if not client:
            raise Exception("No API")

        if context_type == "data_upload":
            prompt = f"""
You are an AI fairness expert.

Dataset has {df.shape[0]} rows and {df.shape[1]} columns.

Column names:
{list(df.columns)}

Give:
1. One quick risk observation
2. Suggest 1–2 sensitive attributes

Keep it short (2-3 lines max).
"""

        elif context_type == "selection":
            prompt = f"""
User selected:
Target: {target}
Protected: {protected_cols}

Comment if this is a good fairness setup or suggest improvement.
Keep it short.
"""

        elif context_type == "analysis":
            prompt = f"""
Fairness gap observed: {stats.get('gap',0)}

Explain in simple terms what this means.
Is it risky?

Keep it short.
"""

        elif context_type == "mitigation":
            prompt = f"""
Bias mitigation applied.

Explain WHY this approach helps reduce bias.
Keep it simple.
"""

        else:
            return ""

        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt
        )

        return response.text

    except:
        # fallback (important)
        if context_type == "data_upload":
            return "Dataset loaded. Check for sensitive attributes like race, gender, or age."
        elif context_type == "selection":
            return "Ensure selected attributes represent meaningful demographic groups."
        elif context_type == "analysis":
            return "Higher gap indicates stronger bias across groups."
        elif context_type == "mitigation":
            return "Rebalancing reduces unequal treatment across groups."

    return ""