import streamlit as st
import google.generativeai as genai
import pandas as pd
from fpdf import FPDF
import os
from dotenv import load_dotenv

# ✅ LOAD ENV VARIABLES
load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# ✅ CONFIGURE GEMINI ONLY IF KEY EXISTS
if GEMINI_API_KEY:
    try:
        genai.configure(api_key=GEMINI_API_KEY)
    except Exception as e:
        st.error(f"Failed to configure Gemini: {e}")
else:
    st.warning("⚠️ Gemini API key not found. Using fallback AI logic.")

def generate_ai_report(audit_results, is_mitigated=False):
    """
    Member 3: The AI Auditor. 
    Converts raw math into an ethical narrative with a safe fallback.
    """
    st.markdown("### 🤖 Member 3: AI Ethical Auditor")

    # 1. Prepare data
    attr = audit_results.get('protected_col', 'Unknown')
    gap = audit_results.get('gap', 0)
    is_class = audit_results.get('is_classification', True)
    metric_type = "Fairness Gap (%)" if is_class else "Disparity Ratio (x)"
    status = "Post-Mitigation" if is_mitigated else "Initial Audit"

    # 2. Build Prompt
    prompt = f"""
    You are an expert AI Ethics Consultant. 
    Status: {status}, Attribute: {attr}, {metric_type}: {gap}.
    Write a professional report: 
    1. Summarize the ethical risk. 2. Explain why it matters. 3. Give one expert tip.
    Keep it in simple language and concise.
    """

    # 3. Call Gemini with a Fallback
    try:
        if GEMINI_API_KEY:
            model = genai.GenerativeModel('gemini-1.5-flash')
            response = model.generate_content(prompt)
            report_text = response.text
            source_label = "Generated by Gemini 1.5 Flash • Strategic Ethical Analysis"
        else:
            raise Exception("No API Key")

    except Exception as e:
        source_label = "AI Auditor Logic • Local Ethical Heuristics"
        if not is_mitigated:
            report_text = f"The audit of **{attr}** reveals a significant {metric_type} of **{gap}**. This disparity suggests that the current model may perpetuate historical inequities, posing a high risk for discriminatory outcomes. Expert Tip: Investigate if this attribute is a proxy for unobserved socioeconomic variables."
        else:
            report_text = f"Mitigation strategies have successfully reduced the disparity in **{attr}**. By balancing sample weights, we have moved the model toward demographic parity while maintaining data integrity. Expert Tip: Monitor model performance over time to ensure fairness holds on new, unseen data."

    # 4. Display result
    with st.container(border=True):
        st.write(report_text)
        st.caption(source_label)

        # PDF DOWNLOAD
        pdf_data = create_pdf(audit_results, report_text)
        st.download_button(
            label="📥 Download PDF Report",
            data=pdf_data,
            file_name="AI_Ethics_Report.pdf",
            mime="application/pdf"
        )

    return {
        "risk": audit_results.get('risk', 'Unknown'),
        "finding": report_text
    }


def show_proxy_warning(df, protected_col):
    numeric_df = df.select_dtypes(include=['number'])

    if protected_col in df.columns and not numeric_df.empty:
        temp_df = df.copy()
        temp_df[protected_col] = temp_df[protected_col].astype('category').cat.codes

        corr = temp_df.corr(numeric_only=True)[protected_col].abs().sort_values(ascending=False)
        proxies = corr[1:3]

        if not proxies.empty and proxies.iloc[0] > 0.5:
            st.warning(
                f"Proxy Detected: **{proxies.index[0]}** is highly correlated ({proxies.iloc[0]:.2f}) with "
                f"**{protected_col}**. Removing the sensitive attribute alone will NOT fix bias!"
            )


def sanitize_text(text):
    if not isinstance(text, str):
        text = str(text)

    replacements = {
        '🔴': 'HIGH RISK',
        '🟡': 'MODERATE',
        '🟢': 'LOW RISK'
    }
    for k, v in replacements.items():
        text = text.replace(k, v)

    text = text.encode('latin-1', 'ignore').decode('latin-1')
    return text


def create_pdf(audit_results, report_text):
    pdf = FPDF()
    pdf.add_page()

    protected = sanitize_text(audit_results.get('protected_col','N/A'))
    gap = sanitize_text(str(audit_results.get('gap',0)))
    risk = sanitize_text(audit_results.get('risk','Unknown'))
    report_text = sanitize_text(report_text)

    pdf.set_font("Arial", 'B', 18)
    pdf.cell(0, 12, "FairFrame AI Audit Report", ln=True, align='C')

    pdf.ln(10)

    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 8, f"Protected Attribute: {protected}", ln=True)
    pdf.cell(0, 8, f"Bias Score: {gap}", ln=True)
    pdf.cell(0, 8, f"Risk: {risk}", ln=True)

    pdf.ln(10)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "AI Ethical Report", ln=True)

    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 8, report_text)

    return pdf.output(dest='S').encode('latin-1', errors='replace')